export type Verb = {
  id: number;
  fstVerbForm: string;
  sndVerbForm: string;
  trdVerbForm: string;
  translateVerb: string;
};

export let verbsArray: Verb[] = [
  {
    id: 0,
    fstVerbForm: "bet",
    sndVerbForm: "bet",
    trdVerbForm: "bet",
    translateVerb: "делать ставку",
  },
  {
    id: 1,
    fstVerbForm: "burst",
    sndVerbForm: "burst",
    trdVerbForm: "burst",
    translateVerb: "лопаться, разрываться",
  },
  {
    id: 2,
    fstVerbForm: "cast",
    sndVerbForm: "cast",
    trdVerbForm: "cast",
    translateVerb: "бросать",
  },
  {
    id: 3,
    fstVerbForm: "cost",
    sndVerbForm: "cost",
    trdVerbForm: "cost",
    translateVerb: "стоить",
  },
  {
    id: 4,
    fstVerbForm: "cut",
    sndVerbForm: "cut",
    trdVerbForm: "cut",
    translateVerb: "резать",
  },
  {
    id: 5,
    fstVerbForm: "fit",
    sndVerbForm: "fit",
    trdVerbForm: "fit",
    translateVerb: "соответствовать, подходить",
  },
  {
    id: 6,
    fstVerbForm: "hit",
    sndVerbForm: "hit",
    trdVerbForm: "hit",
    translateVerb: "ударять",
  },
  {
    id: 7,
    fstVerbForm: "read",
    sndVerbForm: "read",
    trdVerbForm: "read",
    translateVerb: "читать",
  },
  {
    id: 8,
    fstVerbForm: "let",
    sndVerbForm: "let",
    trdVerbForm: "let",
    translateVerb: "позволять",
  },
  {
    id: 9,
    fstVerbForm: "put",
    sndVerbForm: "put",
    trdVerbForm: "put",
    translateVerb: "класть",
  },
  {
    id: 10,
    fstVerbForm: "hurt",
    sndVerbForm: "hurt",
    trdVerbForm: "hurt",
    translateVerb: "ранить, причинять боль",
  },
  {
    id: 11,
    fstVerbForm: "set",
    sndVerbForm: "set",
    trdVerbForm: "set",
    translateVerb: "устанавливать",
  },
  {
    id: 12,
    fstVerbForm: "upset",
    sndVerbForm: "upset",
    trdVerbForm: "upset",
    translateVerb: "расстраивать",
  },
  {
    id: 13,
    fstVerbForm: "shut",
    sndVerbForm: "shut",
    trdVerbForm: "shut",
    translateVerb: "закрывать",
  },
  {
    id: 14,
    fstVerbForm: "quit",
    sndVerbForm: "quit",
    trdVerbForm: "quit",
    translateVerb: "уволиться, покидать",
  },
  {
    id: 15,
    fstVerbForm: "spread",
    sndVerbForm: "spread",
    trdVerbForm: "spread",
    translateVerb: "распространять",
  },
  {
    id: 16,
    fstVerbForm: "wet",
    sndVerbForm: "wet",
    trdVerbForm: "wet",
    translateVerb: "поливать, мочить",
  },
  {
    id: 17,
    fstVerbForm: "input",
    sndVerbForm: "input",
    trdVerbForm: "input",
    translateVerb: "вводить",
  },
  {
    id: 18,
    fstVerbForm: "output",
    sndVerbForm: "output",
    trdVerbForm: "output",
    translateVerb: "выводить",
  },
  {
    id: 19,
    fstVerbForm: "knit",
    sndVerbForm: "knit",
    trdVerbForm: "knit",
    translateVerb: "вязать",
  },
  {
    id: 20,
    fstVerbForm: "come",
    sndVerbForm: "came",
    trdVerbForm: "come",
    translateVerb: "приходить",
  },
  {
    id: 21,
    fstVerbForm: "become",
    sndVerbForm: "became",
    trdVerbForm: "become",
    translateVerb: "становиться",
  },
  {
    id: 22,
    fstVerbForm: "run",
    sndVerbForm: "ran",
    trdVerbForm: "run",
    translateVerb: "бегать",
  },
  {
    id: 23,
    fstVerbForm: "swing",
    sndVerbForm: "swung",
    trdVerbForm: "swung",
    translateVerb: "качать, раскачивать",
  },
  {
    id: 24,
    fstVerbForm: "buy",
    sndVerbForm: "bought",
    trdVerbForm: "bought",
    translateVerb: "покупать",
  },
  {
    id: 25,
    fstVerbForm: "bring",
    sndVerbForm: "brought",
    trdVerbForm: "brought",
    translateVerb: "приносить",
  },
  {
    id: 26,
    fstVerbForm: "catch",
    sndVerbForm: "caught",
    trdVerbForm: "caught",
    translateVerb: "ловить",
  },
  {
    id: 27,
    fstVerbForm: "fight",
    sndVerbForm: "fought",
    trdVerbForm: "fought",
    translateVerb: "драться, бороться",
  },
  {
    id: 28,
    fstVerbForm: "teach",
    sndVerbForm: "taught",
    trdVerbForm: "taught",
    translateVerb: "учить",
  },
  {
    id: 29,
    fstVerbForm: "think",
    sndVerbForm: "thought",
    trdVerbForm: "thought",
    translateVerb: "думать",
  },
  {
    id: 30,
    fstVerbForm: "seek",
    sndVerbForm: "sought",
    trdVerbForm: "sought",
    translateVerb: "искать",
  },
  {
    id: 31,
    fstVerbForm: "may",
    sndVerbForm: "might",
    trdVerbForm: "might",
    translateVerb: "мочь",
  },
  {
    id: 32,
    fstVerbForm: "break",
    sndVerbForm: "broke",
    trdVerbForm: "broken",
    translateVerb: "ломать",
  },
  {
    id: 33,
    fstVerbForm: "choose",
    sndVerbForm: "chose",
    trdVerbForm: "chosen",
    translateVerb: "выбирать",
  },
  {
    id: 34,
    fstVerbForm: "drive",
    sndVerbForm: "drove",
    trdVerbForm: "driven",
    translateVerb: "водить, ехать",
  },
  {
    id: 35,
    fstVerbForm: "forget",
    sndVerbForm: "forgot",
    trdVerbForm: "forgotten",
    translateVerb: "забывать",
  },
  {
    id: 36,
    fstVerbForm: "freeze",
    sndVerbForm: "froze",
    trdVerbForm: "frozen",
    translateVerb: "замерзать",
  },
  {
    id: 37,
    fstVerbForm: "get",
    sndVerbForm: "got",
    trdVerbForm: "gotten",
    translateVerb: "получать",
  },
  {
    id: 38,
    fstVerbForm: "ride",
    sndVerbForm: "rode",
    trdVerbForm: "ridden",
    translateVerb: "ехать, кататься",
  },
  {
    id: 39,
    fstVerbForm: "rise",
    sndVerbForm: "rose",
    trdVerbForm: "risen",
    translateVerb: "вставать, подниматься",
  },
  {
    id: 40,
    fstVerbForm: "speak",
    sndVerbForm: "spoke",
    trdVerbForm: "spoken",
    translateVerb: "говорить",
  },
  {
    id: 41,
    fstVerbForm: "steal",
    sndVerbForm: "stole",
    trdVerbForm: "stolen",
    translateVerb: "красть",
  },
  {
    id: 42,
    fstVerbForm: "tear",
    sndVerbForm: "tore",
    trdVerbForm: "torn",
    translateVerb: "рвать",
  },
  {
    id: 43,
    fstVerbForm: "wake",
    sndVerbForm: "woke",
    trdVerbForm: "woken",
    translateVerb: "просыпаться",
  },
  {
    id: 44,
    fstVerbForm: "awake",
    sndVerbForm: "awoke",
    trdVerbForm: "awoken",
    translateVerb: "пробуждаться",
  },
  {
    id: 45,
    fstVerbForm: "wear",
    sndVerbForm: "wore",
    trdVerbForm: "worn",
    translateVerb: "носить",
  },
  {
    id: 46,
    fstVerbForm: "write",
    sndVerbForm: "wrote",
    trdVerbForm: "written",
    translateVerb: "писать",
  },
  {
    id: 47,
    fstVerbForm: "be",
    sndVerbForm: "was/were",
    trdVerbForm: "been",
    translateVerb: "быть",
  },
  {
    id: 48,
    fstVerbForm: "eat",
    sndVerbForm: "ate",
    trdVerbForm: "eaten",
    translateVerb: "есть",
  },
  {
    id: 49,
    fstVerbForm: "do",
    sndVerbForm: "did",
    trdVerbForm: "done",
    translateVerb: "делать",
  },
  {
    id: 50,
    fstVerbForm: "give",
    sndVerbForm: "gave",
    trdVerbForm: "given",
    translateVerb: "давать",
  },
  {
    id: 51,
    fstVerbForm: "forgive",
    sndVerbForm: "forgave",
    trdVerbForm: "forgiven",
    translateVerb: "прощать",
  },
  {
    id: 52,
    fstVerbForm: "go",
    sndVerbForm: "went",
    trdVerbForm: "gone",
    translateVerb: "идти",
  },
  {
    id: 53,
    fstVerbForm: "take",
    sndVerbForm: "took",
    trdVerbForm: "taken",
    translateVerb: "брать",
  },
  {
    id: 54,
    fstVerbForm: "mistake",
    sndVerbForm: "mistook",
    trdVerbForm: "mistaken",
    translateVerb: "ошибаться",
  },
  {
    id: 55,
    fstVerbForm: "see",
    sndVerbForm: "saw",
    trdVerbForm: "seen",
    translateVerb: "видеть",
  },
  {
    id: 56,
    fstVerbForm: "bear",
    sndVerbForm: "bore",
    trdVerbForm: "born",
    translateVerb: "рожать",
  },
  {
    id: 57,
    fstVerbForm: "fall",
    sndVerbForm: "fell",
    trdVerbForm: "fallen",
    translateVerb: "падать",
  },
  {
    id: 58,
    fstVerbForm: "draw",
    sndVerbForm: "drew",
    trdVerbForm: "drawn",
    translateVerb: "рисовать",
  },
  {
    id: 59,
    fstVerbForm: "beat",
    sndVerbForm: "beat",
    trdVerbForm: "beaten",
    translateVerb: "бить",
  },
  {
    id: 60,
    fstVerbForm: "lie",
    sndVerbForm: "lay",
    trdVerbForm: "lain",
    translateVerb: "лежать",
  },
  {
    id: 61,
    fstVerbForm: "shake",
    sndVerbForm: "shook",
    trdVerbForm: "shaken",
    translateVerb: "трясти",
  },
  {
    id: 62,
    fstVerbForm: "show",
    sndVerbForm: "showed",
    trdVerbForm: "shown",
    translateVerb: "показывать",
  },
  {
    id: 63,
    fstVerbForm: "hide",
    sndVerbForm: "hid",
    trdVerbForm: "hidden",
    translateVerb: "прятать",
  },
  {
    id: 64,
    fstVerbForm: "have",
    sndVerbForm: "had",
    trdVerbForm: "had",
    translateVerb: "иметь",
  },
  {
    id: 65,
    fstVerbForm: "make",
    sndVerbForm: "made",
    trdVerbForm: "made",
    translateVerb: "делать, создавать",
  },
  {
    id: 66,
    fstVerbForm: "remake",
    sndVerbForm: "remade",
    trdVerbForm: "remade",
    translateVerb: "переделывать",
  },
  {
    id: 67,
    fstVerbForm: "tell",
    sndVerbForm: "told",
    trdVerbForm: "told",
    translateVerb: "рассказывать",
  },
  {
    id: 68,
    fstVerbForm: "pay",
    sndVerbForm: "paid",
    trdVerbForm: "paid",
    translateVerb: "платить",
  },
  {
    id: 69,
    fstVerbForm: "say",
    sndVerbForm: "said",
    trdVerbForm: "said",
    translateVerb: "говорить",
  },
  {
    id: 70,
    fstVerbForm: "stand",
    sndVerbForm: "stood",
    trdVerbForm: "stood",
    translateVerb: "стоять",
  },
  {
    id: 71,
    fstVerbForm: "understand",
    sndVerbForm: "understood",
    trdVerbForm: "understood",
    translateVerb: "понимать",
  },
  {
    id: 72,
    fstVerbForm: "misunderstand",
    sndVerbForm: "misunderstood",
    trdVerbForm: "misunderstood",
    translateVerb: "неправильно понимать",
  },
  {
    id: 73,
    fstVerbForm: "win",
    sndVerbForm: "won",
    trdVerbForm: "won",
    translateVerb: "выигрывать",
  },
  {
    id: 74,
    fstVerbForm: "feed",
    sndVerbForm: "fed",
    trdVerbForm: "fed",
    translateVerb: "кормить",
  },
  {
    id: 75,
    fstVerbForm: "find",
    sndVerbForm: "found",
    trdVerbForm: "found",
    translateVerb: "находить",
  },
  {
    id: 76,
    fstVerbForm: "hold",
    sndVerbForm: "held",
    trdVerbForm: "held",
    translateVerb: "держать",
  },
  {
    id: 77,
    fstVerbForm: "sell",
    sndVerbForm: "sold",
    trdVerbForm: "sold",
    translateVerb: "продавать",
  },
  {
    id: 78,
    fstVerbForm: "stick",
    sndVerbForm: "stuck",
    trdVerbForm: "stuck",
    translateVerb: "приклеивать, застревать",
  },
  {
    id: 79,
    fstVerbForm: "hang",
    sndVerbForm: "hung",
    trdVerbForm: "hung",
    translateVerb: "вешать",
  },
  {
    id: 80,
    fstVerbForm: "hear",
    sndVerbForm: "heard",
    trdVerbForm: "heard",
    translateVerb: "слышать",
  },
  {
    id: 81,
    fstVerbForm: "lay",
    sndVerbForm: "laid",
    trdVerbForm: "laid",
    translateVerb: "класть, положить",
  },
  {
    id: 82,
    fstVerbForm: "lead",
    sndVerbForm: "led",
    trdVerbForm: "led",
    translateVerb: "вести",
  },
  {
    id: 83,
    fstVerbForm: "shine",
    sndVerbForm: "shone",
    trdVerbForm: "shone",
    translateVerb: "светить",
  },
  {
    id: 84,
    fstVerbForm: "slide",
    sndVerbForm: "slid",
    trdVerbForm: "slid",
    translateVerb: "скользить",
  },
  {
    id: 85,
    fstVerbForm: "bind",
    sndVerbForm: "bound",
    trdVerbForm: "bound",
    translateVerb: "связывать",
  },
  {
    id: 86,
    fstVerbForm: "dig",
    sndVerbForm: "dug",
    trdVerbForm: "dug",
    translateVerb: "копать",
  },
  {
    id: 87,
    fstVerbForm: "blow",
    sndVerbForm: "blew",
    trdVerbForm: "blown",
    translateVerb: "дуть",
  },
  {
    id: 88,
    fstVerbForm: "fly",
    sndVerbForm: "flew",
    trdVerbForm: "flown",
    translateVerb: "летать",
  },
  {
    id: 89,
    fstVerbForm: "grow",
    sndVerbForm: "grew",
    trdVerbForm: "grown",
    translateVerb: "расти",
  },
  {
    id: 90,
    fstVerbForm: "throw",
    sndVerbForm: "threw",
    trdVerbForm: "thrown",
    translateVerb: "бросать",
  },
  {
    id: 91,
    fstVerbForm: "know",
    sndVerbForm: "knew",
    trdVerbForm: "known",
    translateVerb: "знать",
  },
  {
    id: 92,
    fstVerbForm: "bend",
    sndVerbForm: "bent",
    trdVerbForm: "bent",
    translateVerb: "гнуть",
  },
  {
    id: 93,
    fstVerbForm: "creep",
    sndVerbForm: "crept",
    trdVerbForm: "crept",
    translateVerb: "ползать",
  },
  {
    id: 94,
    fstVerbForm: "dream",
    sndVerbForm: "dreamt",
    trdVerbForm: "dreamt",
    translateVerb: "мечтать",
  },
  {
    id: 95,
    fstVerbForm: "feel",
    sndVerbForm: "felt",
    trdVerbForm: "felt",
    translateVerb: "чувствовать",
  },
  {
    id: 96,
    fstVerbForm: "keep",
    sndVerbForm: "kept",
    trdVerbForm: "kept",
    translateVerb: "хранить, сохранять",
  },
  {
    id: 97,
    fstVerbForm: "kneel",
    sndVerbForm: "knelt",
    trdVerbForm: "knelt",
    translateVerb: "становиться на колени",
  },
  {
    id: 98,
    fstVerbForm: "leave",
    sndVerbForm: "left",
    trdVerbForm: "left",
    translateVerb: "оставлять, покидать",
  },
  {
    id: 99,
    fstVerbForm: "lend",
    sndVerbForm: "lent",
    trdVerbForm: "lent",
    translateVerb: "давать в долг",
  },
  {
    id: 100,
    fstVerbForm: "mean",
    sndVerbForm: "meant",
    trdVerbForm: "meant",
    translateVerb: "означать",
  },
  {
    id: 101,
    fstVerbForm: "meet",
    sndVerbForm: "met",
    trdVerbForm: "met",
    translateVerb: "встречать",
  },
  {
    id: 102,
    fstVerbForm: "send",
    sndVerbForm: "sent",
    trdVerbForm: "sent",
    translateVerb: "посылать",
  },
  {
    id: 103,
    fstVerbForm: "spend",
    sndVerbForm: "spent",
    trdVerbForm: "spent",
    translateVerb: "тратить",
  },
  {
    id: 104,
    fstVerbForm: "build",
    sndVerbForm: "built",
    trdVerbForm: "built",
    translateVerb: "строить",
  },
  {
    id: 105,
    fstVerbForm: "lose",
    sndVerbForm: "lost",
    trdVerbForm: "lost",
    translateVerb: "терять",
  },
  {
    id: 106,
    fstVerbForm: "learn",
    sndVerbForm: "learnt",
    trdVerbForm: "learnt",
    translateVerb: "учить, изучать",
  },
  {
    id: 107,
    fstVerbForm: "sit",
    sndVerbForm: "sat",
    trdVerbForm: "sat",
    translateVerb: "сидеть",
  },
  {
    id: 108,
    fstVerbForm: "sleep",
    sndVerbForm: "slept",
    trdVerbForm: "slept",
    translateVerb: "спать",
  },
  {
    id: 109,
    fstVerbForm: "smell",
    sndVerbForm: "smelt",
    trdVerbForm: "smelt",
    translateVerb: "пахнуть, чувствовать запах",
  },
  {
    id: 110,
    fstVerbForm: "spell",
    sndVerbForm: "spelt",
    trdVerbForm: "spelt",
    translateVerb: "произносить по буквам",
  },
  {
    id: 111,
    fstVerbForm: "burn",
    sndVerbForm: "burnt",
    trdVerbForm: "burnt",
    translateVerb: "сжигать",
  },
  {
    id: 112,
    fstVerbForm: "shoot",
    sndVerbForm: "shot",
    trdVerbForm: "shot",
    translateVerb: "стрелять",
  },
  {
    id: 113,
    fstVerbForm: "spill",
    sndVerbForm: "spilt",
    trdVerbForm: "spilt",
    translateVerb: "проливать",
  },
  {
    id: 114,
    fstVerbForm: "spoil",
    sndVerbForm: "spoilt",
    trdVerbForm: "spoilt",
    translateVerb: "портить",
  },
  {
    id: 115,
    fstVerbForm: "light",
    sndVerbForm: "lit",
    trdVerbForm: "lit",
    translateVerb: "зажигать",
  },
  {
    id: 116,
    fstVerbForm: "deal",
    sndVerbForm: "dealt",
    trdVerbForm: "dealt",
    translateVerb: "иметь дело, справляться",
  },
  {
    id: 117,
    fstVerbForm: "weep",
    sndVerbForm: "wept",
    trdVerbForm: "wept",
    translateVerb: "плакать",
  },
  {
    id: 118,
    fstVerbForm: "begin",
    sndVerbForm: "began",
    trdVerbForm: "begun",
    translateVerb: "начинать",
  },
  {
    id: 119,
    fstVerbForm: "drink",
    sndVerbForm: "drank",
    trdVerbForm: "drunk",
    translateVerb: "пить",
  },
  {
    id: 120,
    fstVerbForm: "swim",
    sndVerbForm: "swam",
    trdVerbForm: "swum",
    translateVerb: "плавать",
  },
  {
    id: 121,
    fstVerbForm: "sing",
    sndVerbForm: "sang",
    trdVerbForm: "sung",
    translateVerb: "петь",
  },
  {
    id: 122,
    fstVerbForm: "ring",
    sndVerbForm: "rang",
    trdVerbForm: "rung",
    translateVerb: "звонить",
  },
  {
    id: 123,
    fstVerbForm: "can",
    sndVerbForm: "could",
    trdVerbForm: "been able",
    translateVerb: "мочь",
  },
];
